ViewModels/DoorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RF_Data_Importer.ViewModels
{
    public class DoorViewModel
    {
        public int Id { get; set; }
        public string Door { get; set; }
        public string Message { get; set; }
    }
}

Controllers/DoorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RF_Data_Importer.Models;
using RF_Data_Importer.Services;

namespace RF_Data_Importer.Controllers
{
    public class DoorController : Controller
    {
        private readonly ILogger<DoorController> _logger;
        private readonly IRFService _service;
        public DoorController(ILogger<DoorController> logger, IRFService rfService)
        {
            _logger = logger;
            _service = rfService;
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormFile file)
        {
            //var modelList = new List<DoorModel>();
            //var message = "";
            //var rowNo = 0;
            //try
            //{
            //    if (ModelState.IsValid)
            //    {
            //        if (file != null && file.Length > 0)
            //        {
            //            if (file.FileName.EndsWith(".txt"))
            //            {
            //                using (var sr = new StreamReader(file.OpenReadStream()))
            //                {
            //                    //// var columnHeader = sr.ReadLine();//// skip the column header
            //                    /////read each line
            //                    string content;
            //                    while ((content = sr.ReadLine()) != null)
            //                    {
            //                        if (!string.IsNullOrEmpty(content))
            //                        {
            //                            rowNo++;
            //                            string[] values = content.Split(new char[] { ',' });
            //                            var model = new DoorModel
            //                            {
            //                                Door = Convert.ToString(values[1]).Replace("\"", ""),
            //                            };
            //                            modelList.Add(model);
            //                        }
            //                    }
            //                }
            //                //// Process the import
            //                rowNo = 0;
            //                foreach (var entity in modelList)
            //                {
            //                    rowNo++;
            //                    //await _service.ImportDoor(entity);
            //                }
            //                message = "Uploaded successfully";
            //            }
            //        }
            //        else
            //        { message = "Nothing to import"; }
            //    }
            //}
            //catch (Exception ex)
            //{
            //    message = $"Error reading row no->{rowNo} - {ex.Message}";
            //}
            //ViewBag.Message = message;

            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Door/Index.cshtml
@model RF_Data_Importer.ViewModels.RFViewModel
@{
    ViewData["Title"] = "Import the Door Master Data";
}

<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">@ViewData["Title"]</h6>
            </div>
            <div class="card-body">
                <form id="frmRFDataImport" asp-controller="Door" asp-action="Index" method="post" enctype="multipart/form-data">
                    <partial name="~/Views/Shared/_FileUpload.cshtml" />
                    @{ string message = @ViewBag.Message == null ? "Please click Browse and choose the file and then click Import" : @ViewBag.Message; }
                    <p class="font-italic p-file mt-2">@Html.Raw(@message)</p>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $("#frmDoor").submit(function (e) {
            if ($("input:file").val() !== '') {
                showSpinner("", true);
            }
        });
    });
</script>